# Generated by Django 5.2.8 on 2025-11-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
