# Generated by Django 5.2.8 on 2025-11-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oyun', '0002_player_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(default='🐍', max_length=10),
        ),
    ]
